/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as ComplaintRouteImport } from './routes/complaint'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EmiRouteImport } from './routes/emi'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SolarPanelsRouteImport } from './routes/solar-panels'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as YojanaRouteImport } from './routes/yojana'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintRoute = ComplaintRouteImport.update({
  id: '/complaint',
  path: '/complaint',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EmiRoute = EmiRouteImport.update({
  id: '/emi',
  path: '/emi',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SolarPanelsRoute = SolarPanelsRouteImport.update({
  id: '/solar-panels',
  path: '/solar-panels',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const YojanaRoute = YojanaRouteImport.update({
  id: '/yojana',
  path: '/yojana',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/calculator': typeof CalculatorRoute
  '/complaint': typeof ComplaintRoute
  '/contact': typeof ContactRoute
  '/emi': typeof EmiRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar-panels': typeof SolarPanelsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/testimonials': typeof TestimonialsRoute
  '/yojana': typeof YojanaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/calculator': typeof CalculatorRoute
  '/complaint': typeof ComplaintRoute
  '/contact': typeof ContactRoute
  '/emi': typeof EmiRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar-panels': typeof SolarPanelsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/testimonials': typeof TestimonialsRoute
  '/yojana': typeof YojanaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/calculator': typeof CalculatorRoute
  '/complaint': typeof ComplaintRoute
  '/contact': typeof ContactRoute
  '/emi': typeof EmiRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar-panels': typeof SolarPanelsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/testimonials': typeof TestimonialsRoute
  '/yojana': typeof YojanaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apply'
    | '/calculator'
    | '/complaint'
    | '/contact'
    | '/emi'
    | '/faqs'
    | '/gallery'
    | '/privacy-policy'
    | '/services'
    | '/sitemap.xml'
    | '/solar-panels'
    | '/terms-and-conditions'
    | '/testimonials'
    | '/yojana'
    | '/admin/login'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apply'
    | '/calculator'
    | '/complaint'
    | '/contact'
    | '/emi'
    | '/faqs'
    | '/gallery'
    | '/privacy-policy'
    | '/services'
    | '/sitemap.xml'
    | '/solar-panels'
    | '/terms-and-conditions'
    | '/testimonials'
    | '/yojana'
    | '/admin/login'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/apply'
    | '/calculator'
    | '/complaint'
    | '/contact'
    | '/emi'
    | '/faqs'
    | '/gallery'
    | '/privacy-policy'
    | '/services'
    | '/sitemap.xml'
    | '/solar-panels'
    | '/terms-and-conditions'
    | '/testimonials'
    | '/yojana'
    | '/admin/login'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApplyRoute: typeof ApplyRoute
  CalculatorRoute: typeof CalculatorRoute
  ComplaintRoute: typeof ComplaintRoute
  ContactRoute: typeof ContactRoute
  EmiRoute: typeof EmiRoute
  FaqsRoute: typeof FaqsRoute
  GalleryRoute: typeof GalleryRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolarPanelsRoute: typeof SolarPanelsRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  YojanaRoute: typeof YojanaRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaint': {
      id: '/complaint'
      path: '/complaint'
      fullPath: '/complaint'
      preLoaderRoute: typeof ComplaintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emi': {
      id: '/emi'
      path: '/emi'
      fullPath: '/emi'
      preLoaderRoute: typeof EmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solar-panels': {
      id: '/solar-panels'
      path: '/solar-panels'
      fullPath: '/solar-panels'
      preLoaderRoute: typeof SolarPanelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yojana': {
      id: '/yojana'
      path: '/yojana'
      fullPath: '/yojana'
      preLoaderRoute: typeof YojanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApplyRoute: ApplyRoute,
  CalculatorRoute: CalculatorRoute,
  ComplaintRoute: ComplaintRoute,
  ContactRoute: ContactRoute,
  EmiRoute: EmiRoute,
  FaqsRoute: FaqsRoute,
  GalleryRoute: GalleryRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolarPanelsRoute: SolarPanelsRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TestimonialsRoute: TestimonialsRoute,
  YojanaRoute: YojanaRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
